### ISSUE TITLE
PicketLink IDM uses JBoss Logger, not included in BOM, error on Glassfish deployment

### ISSUE THREAD

**Issue by agois-inc** [picketlink/picketlink-idm#3]
It looks like PicketLink requires dependency "org.jboss.logging:jboss-logging" which is not part of the BOM for 2.5.3-Beta1.  This is a problem for non-JBoss builds/deployments.  

Can you either:
1. Include this in the BOM
   
   ```
   <dependency>
       <groupId>org.jboss.logging</groupId>
       <artifactId>jboss-logging</artifactId>
       <version>3.1.4.GA</version>
   </dependency>
   ```
2. Use "java.util.logging.Logger" instead of "org.jboss.logging.Logger"

Here is the error:
SEVERE:   Exception while invoking class org.glassfish.ejb.startup.EjbApplication start method
javax.ejb.EJBException: javax.ejb.CreateException: Initialization failed for Singleton IDMInitializer
    at com.sun.ejb.containers.AbstractSingletonContainer$SingletonContextFactory.create(AbstractSingletonContainer.java:656)
    at com.sun.ejb.containers.AbstractSingletonContainer.instantiateSingletonInstance(AbstractSingletonContainer.java:396)
    ...
    at java.lang.Thread.run(Thread.java:724)
Caused by: java.lang.NoClassDefFoundError: org/jboss/logging/Logger
    at org.picketlink.common.DefaultPicketLinkLogger.<init>(DefaultPicketLinkLogger.java:60)
    at org.picketlink.common.PicketLinkLoggerFactory.<clinit>(PicketLinkLoggerFactory.java:38)
    at org.picketlink.common.util.StringUtil.<clinit>(StringUtil.java:44)
    at org.picketlink.idm.config.NamedIdentityConfigurationBuilder.<init>(NamedIdentityConfigurationBuilder.java:38)
    at org.picketlink.idm.config.IdentityConfigurationBuilder.named(IdentityConfigurationBuilder.java:75)
    at org.jboss.as.quickstarts.picketlink.authorization.idm.jpa.IDMConfiguration.initConfig(IDMConfiguration.java:68)
    at org.jboss.as.quickstarts.picketlink.authorization.idm.jpa.IDMConfiguration.createConfig(IDMConfiguration.java:54)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.jboss.weld.injection.MethodInjectionPoint.invokeOnInstanceWithSpecialValue(MethodInjectionPoint.java:93)
    ... 92 more
Caused by: java.lang.ClassNotFoundException: org.jboss.logging.Logger
    at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1761)
    at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1611)
    ... 104 more

Caused by: javax.enterprise.inject.CreationException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    ...
    at org.picketlink.producer.IdentityManagerProducer.getIdentityConfiguration(IdentityManagerProducer.java:180)
    at org.picketlink.producer.IdentityManagerProducer.createIdentityConfigurationBuilder(IdentityManagerProducer.java:154)
    at org.picketlink.producer.IdentityManagerProducer.createEmbeddedPartitionManager(IdentityManagerProducer.java:193)
    at org.picketlink.producer.IdentityManagerProducer.init(IdentityManagerProducer.java:111)
    ...
    ... 44 more
Caused by: java.lang.NoClassDefFoundError: org/jboss/logging/Logger
    at org.picketlink.common.DefaultPicketLinkLogger.<init>(DefaultPicketLinkLogger.java:60)
    at org.picketlink.common.PicketLinkLoggerFactory.<clinit>(PicketLinkLoggerFactory.java:38)
    at org.picketlink.common.util.StringUtil.<clinit>(StringUtil.java:44)
    at org.picketlink.idm.config.NamedIdentityConfigurationBuilder.<init>(NamedIdentityConfigurationBuilder.java:38)
    at org.picketlink.idm.config.IdentityConfigurationBuilder.named(IdentityConfigurationBuilder.java:75)
    at org.jboss.as.quickstarts.picketlink.authorization.idm.jpa.IDMConfiguration.initConfig(IDMConfiguration.java:68)
    at org.jboss.as.quickstarts.picketlink.authorization.idm.jpa.IDMConfiguration.createConfig(IDMConfiguration.java:54)
    ... 92 more
Caused by: java.lang.ClassNotFoundException: org.jboss.logging.Logger
    at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1761)
    at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1611)
    ... 104 more

SEVERE:   Exception while loading the app
SEVERE:   Undeployment failed for context /picketlink-authorization-idm-jpa
SEVERE:   Exception while loading the app : javax.ejb.CreateException: Initialization failed for Singleton IDMInitializer
javax.ejb.CreateException: Initialization failed for Singleton IDMInitializer
    at java.lang.Thread.run(Thread.java:724)
Caused by: javax.enterprise.inject.CreationException
    ...
    at org.picketlink.producer.IdentityManagerProducer.getIdentityConfiguration(IdentityManagerProducer.java:180)
    at org.picketlink.producer.IdentityManagerProducer.createIdentityConfigurationBuilder(IdentityManagerProducer.java:154)
    at org.picketlink.producer.IdentityManagerProducer.createEmbeddedPartitionManager(IdentityManagerProducer.java:193)
    at org.picketlink.producer.IdentityManagerProducer.init(IdentityManagerProducer.java:111)
    ...
    ... 44 more
Caused by: java.lang.NoClassDefFoundError: org/jboss/logging/Logger
    at org.picketlink.common.DefaultPicketLinkLogger.<init>(DefaultPicketLinkLogger.java:60)
    at org.picketlink.common.PicketLinkLoggerFactory.<clinit>(PicketLinkLoggerFactory.java:38)
    at org.picketlink.common.util.StringUtil.<clinit>(StringUtil.java:44)
    at org.picketlink.idm.config.NamedIdentityConfigurationBuilder.<init>(NamedIdentityConfigurationBuilder.java:38)
    at org.picketlink.idm.config.IdentityConfigurationBuilder.named(IdentityConfigurationBuilder.java:75)
    at org.jboss.as.quickstarts.picketlink.authorization.idm.jpa.IDMConfiguration.initConfig(IDMConfiguration.java:68)
    at org.jboss.as.quickstarts.picketlink.authorization.idm.jpa.IDMConfiguration.createConfig(IDMConfiguration.java:54)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.jboss.weld.injection.MethodInjectionPoint.invokeOnInstanceWithSpecialValue(MethodInjectionPoint.java:93)
    ... 92 more
Caused by: java.lang.ClassNotFoundException: org.jboss.logging.Logger
    at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1761)
    at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1611)
    ... 104 more

**Comment by pedroigor** [comment]
This repository is no longer maintained and is archived. For more details, please take a look at http://picketlink.org/keycloak-merge-faq.
